name: 'Lint'
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install modules
      run: yarn
    - name: Run lint
      run: yarn run lint
