name: 'Run Jest Tests'
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install modules
      run: yarn
    - name: Run jest tests
      run: yarn run test --maxWorkers=2 --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
